Repository Linaeformin/schello, pull requests merged in 2025-06, with the labels that each got.

#41 [FEAT#40] BE_프로필 이메일 가져오기
  Schello/settings.py
Labels: feature, BE

#42 Design: 홈화면 & 일정추가 및 수정 css 수정 완료
  accounts/static/accounts/profile.js
  accounts/templates/accounts/profile.html
  home/static/home.css
  home/static/home.js
  schedules/static/schedules/todo.css
  schedules/templates/schedules/add-todo-sheet.html
  static/bottomSheetHandler.js
  static/navbar.css
  templates/nav-bar.html
Labels: FE

#45 [REFACTOR#44] BE_파일 디렉토리 수정
  Schello/settings.py
  Schello/urls.py
  accounts/static/accounts/default-profile.png
  accounts/templates/accounts/profile.html
  accounts/views.py
  home/static/home.js
  home/templates/home/home.html
  schedules/templates/schedules/add-todo-sheet.html
  templates/base.html
  templates/nav-bar.html
Labels: BE, FE, refactor

#53 [FEAT#52] BE_바텀 네비게이션 뷰 아이템과 페이지 연결
  static/bottomSheetHandler.js
  templates/base.html
  templates/nav-bar.html
Labels: feature, BE

#67 [FEAT#60] BE_프로필 기본 이미지, 스플래시 화면 연동
  .gitignore
  Schello/settings.py
  Schello/urls.py
  accounts/signals.py
  accounts/static/accounts/images/default.png
  accounts/views.py
  static/splash_screen.js
  templates/splash_screen.html
Labels: feature, BE, FE

#68 [FEAT#60] BE_기본 프로필 이미지 추가 및 settings.py 추적 해제
  .gitignore
  Schello/settings.py
  media/profile_images/default.png
Labels: feature, BE

#71 [fix] 일정추가 css 수정
  accounts/static/accounts/profile.css
  accounts/static/accounts/profile.js
  accounts/templates/accounts/profile.html
  home/static/home.js
  media/profile_images/bulgogi.PNG
  requirements.txt
  schedules/static/schedules/todo.css
  static/bottomSheetHandler.js
  templates/nav-bar.html
Labels: FE, fix

#76 [FEAT#75] BE_일정 삭제 구현
  home/static/home.js
  home/urls.py
  home/views.py
  media/profile_images/스크린샷 2025-06-06 오후 10.25.50.png
  media/profile_images/스크린샷 2025-06-10 오전 2.04.51.png
  media/profile_images/스크린샷 2025-06-10 오전 2.20.37.png
  schedules/views.py
Labels: feature, BE

#84 [DESIGN#83] FE_more-btn 간격 통일
  home/static/home.css
Labels: FE, Design
